<script setup lang="ts">
import { ref } from 'vue';
import RfidSimulationResult from '../components/RfidSimulationResult.vue';
import type { Reading } from '../data/mockData';
type Card = { id: number; uid: string; usuario: string; estado: string; fecha: string };
const props = defineProps<{ cards: Card[] }>();
const simulation = ref({ card: props.cards[0].uid, locker: '02', mode: 'user' });
const result = ref<Reading | null>(null);
function simulate() { const card = props.cards.find((item) => item.uid === simulation.value.card); const allowed = simulation.value.mode === 'admin' || (card?.usuario === 'Carlos Mendoza' && simulation.value.locker === '02') || (card?.usuario === 'María Fernández' && simulation.value.locker === '03'); result.value = { fecha: 'Ahora', uid: simulation.value.mode === 'admin' ? 'ADMIN' : simulation.value.card, usuario: simulation.value.mode === 'admin' ? 'Administrador' : card?.usuario || 'Tarjeta desconocida', locker: `Locker ${simulation.value.locker}`, dispositivo: 'ESP32-LOCKER-01', tipo: simulation.value.mode, resultado: allowed ? 'permitido' : 'denegado', motivo: allowed ? (simulation.value.mode === 'admin' ? 'Apertura administrativa' : 'Locker asignado') : 'Locker asignado a otro usuario' }; }
</script>

<template><div class="section-heading"><div><span class="eyebrow">LABORATORIO DE ACCESO</span><h2>Simulador RFID</h2><p>Explora el flujo de autorización antes de conectar el hardware físico.</p></div><span class="simulation-tag large">SIMULACIÓN · HARDWARE NO CONECTADO</span></div><div class="simulator-grid"><section class="panel simulation-form"><div class="panel-heading"><div><span class="eyebrow">ENTRADA DE EVENTO</span><h3>Configurar lectura</h3></div><span class="scan-mark">◎</span></div><label>Dispositivo<select><option>ESP32-LOCKER-01</option><option>ESP32-LOCKER-02</option></select></label><label>Tarjeta<select v-model="simulation.card"><option v-for="card in cards" :key="card.uid" :value="card.uid">{{ card.usuario }} · {{ card.uid }}</option></select></label><label>Locker<select v-model="simulation.locker"><option>01</option><option>02</option><option>03</option></select></label><label>Tipo de acceso<select v-model="simulation.mode"><option value="user">Usuario</option><option value="admin">Administrador</option></select></label><button class="primary-button" @click="simulate">Simular lectura RFID <span>→</span></button></section><RfidSimulationResult v-if="result" :result="result" /><div v-else class="empty-simulation"><span>◎</span><h3>Listo para simular</h3><p>Configura una tarjeta y ejecuta una lectura para ver la respuesta del sistema.</p></div></div></template>
